version: 2
updates:
  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: pub
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /tools/screenshots
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
